<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-MoreMath.App-7e3fc947-f24a-4f2e-993e-f926e12651ea</UserSecretsId>
    <DartSassMessageLevel>High</DartSassMessageLevel>
  </PropertyGroup>

  <ItemGroup>
    <SassFile Remove="Components\Layout\MainLayout.razor.scss" />
    <SassFile Remove="Components\Layout\NavMenu.razor.scss" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MoreMath.Api.Requests\MoreMath.Api.Requests.csproj" />
    <ProjectReference Include="..\..\MoreMath.Dto\MoreMath.Dto.csproj" />
    <ProjectReference Include="..\..\MoreMath.Infrastructure\MoreMath.Infrastructure.csproj" />
    <ProjectReference Include="..\..\MoreMath.Shared\MoreMath.Shared.csproj" />
    <ProjectReference Include="..\MoreMath.App.Client\MoreMath.App.Client.csproj" />
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="DartSassBuilder" Version="1.1.0" />
    <PackageReference Include="MailKit" Version="4.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Syncfusion.Blazor.Core" Version="27.2.2" />
    <PackageReference Include="Syncfusion.Blazor.Data" Version="27.2.2" />
    <PackageReference Include="Syncfusion.Blazor.DataForm" Version="27.2.2" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="27.2.2" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="27.2.2" />
    <PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\Layout\MainLayout.razor.scss" />
    <None Include="Components\Layout\NavMenu.razor.scss" />
  </ItemGroup>

  <ItemGroup>
    <SassFile Include="wwwroot/scss/styles.scss" />
    <SassFile Include="Components/**/*.scss" />
    <!--<SassFile Include="Styles/**/*.scss" Exclude="Styles/unused/**" />-->
  </ItemGroup>

  <ItemGroup>
    <None Remove="Components\Pages\MathHebrewTableQ.razor.bak" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\Pages\MathHebrewTableQ.razor.bak" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\customized\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\SfResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SfResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Cards\AllArticlesCard.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Cards\ArticleCard.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\ContentBlocks\AuthorLink.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\ContentBlocks\IconLink.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Layout\ColumnLayout.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Pages\Author.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Components\Pages\MathHebrewTableS.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="wwwroot\scss\article-racks.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\SfResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SfResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SfResources.ru.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <SassFile Update="wwwroot\scss\article-racks.scss">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </SassFile>
  </ItemGroup>

</Project>
